apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#Add label to all resources.
commonLabels:
  env: sandbox

#Adds namespacce to all resources.
namespace: sandbox-namespace


bases:
- ../base
resources:
- resource-quota.yaml
- memory-defaults.yaml
- cpu-defaults.yaml
- deployer-role.yaml
- deployer-roleBinding.yaml




