bases:
- ../../base

patchesStrategicMerge:
- replica-and-rollout-strategy.yaml
- nodeport-service.yaml
- cpu-reqs.yaml
- memory-reqs.yaml

  
namePrefix: "sandbox-"
namespace: sandbox-namespace
commonLabels:
  env : sandbox

#Add replicas   
replicas:
- name: app1
  count: 1

images:
- name: nginx
  newName: nginx
  newTag: 1.18.0
  #Use git hash for image
  #  digest: sha256:24a0c4b4a4c0eb97a1aabb8e29f18e917d05abfe1b7a7c07857230879ce7d3d3
