apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  template:
    metadata:
      labels:
        name: app1
    spec:
      containers:
      - name: app1  
        resources:
          limits:
            memory: "50Mi"
          requests:
            memory: "10Mi"

