apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: app1
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: app1
    spec:
      containers:
      - image: nginx:1.17.10
        name: app1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: "1"
          requests:
            memory: "50Mi"
            cpu: "0.5"
status: {}
