apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: app1
  name: app1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: app1
status:
  loadBalancer: {}
